export const AUTH_STEPS = {
  WELCOME: "welcome",
  EMAIL_LOGIN: "email-login",
  EMAIL_REGISTER: "email-register",
  OAUTH_CALLBACK: "oauth-callback",
  ROLE_SELECT: "role-select",
  USER_PROFILE: "user-profile",
  BUSINESS_DATA: "business-data",
  BUSINESS_CATEGORY: "business-category",
  USER_ADDRESS: "user-address",
  ACCOUNT_VERIFY_PROMPT: "account-verify-prompt",
  ACCOUNT_VERIFY: "account-verify",
  VERIFY_EMAIL: "verify-email",
  ACCOUNT_VERIFY_METHOD: "account-verify-method",
  ACCOUNT_VERIFY_READY: "account-verify-ready",
  ADD_PASSWORD: "add-password",
  ADD_MFA: "add-mfa",
  PENDING: "pending",
  ERROR: "error",
};

export const AUTH_FORM_STEPS = {
  USER_PROFILE: "user-profile",
  BUSINESS: "business-data",
  BUSINESS_CATEGORY: "business-category",
  USER_ADDRESS: "user-address",
  ACCOUNT_VERIFY: "account-verify",
  ACCOUNT_VERIFY_PROMPT: "account-verify-prompt",
  VERIFY_EMAIL: "verify-email",
  ACCOUNT_VERIFY_METHOD: "account-verify-method",
  ACCOUNT_VERIFY_READY: "account-verify-ready",
  ADD_PASSWORD: "add-password",
  ADD_MFA: "add-mfa",
};
