export const ADMIN_DOC_GROUPS = [
  { key: "general", label: "General del repo" },
  { key: "referidos_app", label: "Referidos App" },
  { key: "prelaunch_web", label: "Prelaunch" },
  { key: "android_app", label: "Android" },
] as const;

export const ADMIN_DOCS_REGISTRY = [
  {
    id: "repo-readme",
    group: "general",
    title: "README del monorepo",
    pathLabel: "README.md",
    summary: "Contexto general del workspace, apps, packages y comandos base.",
  },
  {
    id: "docs-index",
    group: "general",
    title: "Indice de documentacion",
    pathLabel: "docs/README.md",
    summary: "Mapa principal de documentacion tecnica y operativa.",
  },
  {
    id: "docs-versioning-core",
    group: "general",
    title: "Versionado completo",
    pathLabel: "docs/referidos-system/README.md",
    summary: "Contrato operativo del sistema de versionado y release management.",
  },
  {
    id: "docs-versioning-quick",
    group: "general",
    title: "Versionado rapido",
    pathLabel: "docs/versioning-system.md",
    summary: "Resumen corto para operar releases sin recorrer toda la guia.",
  },
  {
    id: "docs-versioning-no-pr-netlify",
    group: "general",
    title: "Versionado sin PR + Netlify",
    pathLabel: "docs/referidos-system/operacion-sin-pr-netlify.md",
    summary: "Runbook detallado para promover y desplegar sin flujo PR tradicional.",
  },
  {
    id: "docs-envs-secrets",
    group: "general",
    title: "Entornos y secrets",
    pathLabel: "docs/referidos-system/entornos-y-secrets.md",
    summary: "Inventario de secretos, ambientes y consideraciones operativas.",
  },
  {
    id: "docs-support-macros-ops-cache",
    group: "general",
    title: "Macros OPS + cache runtime",
    pathLabel: "docs/referidos-system/support-macros-ops-cache.md",
    summary: "Explica el catalogo runtime de macros y la sincronizacion OPS.",
  },
  {
    id: "pwa-docs-readme",
    group: "referidos_app",
    title: "PWA docs",
    pathLabel: "apps/referidos-app/docs/README.md",
    summary: "Guia funcional y tecnica de la app web principal.",
  },
  {
    id: "prelaunch-docs-readme",
    group: "prelaunch_web",
    title: "Prelaunch docs",
    pathLabel: "apps/prelaunch/docs/README.md",
    summary: "Documentacion de la app prelaunch y sus contratos asociados.",
  },
  {
    id: "android-docs-readme",
    group: "android_app",
    title: "Android docs",
    pathLabel: "apps/referidos-android/docs/README.md",
    summary: "Documentacion operativa especifica de la app Android.",
  },
  {
    id: "android-readme",
    group: "android_app",
    title: "Android README tecnico",
    pathLabel: "apps/referidos-android/README.md",
    summary: "Setup local, build y consideraciones tecnicas de React Native.",
  },
  {
    id: "android-migration",
    group: "android_app",
    title: "Android migration plan",
    pathLabel: "docs/android-migration-plan.md",
    summary: "Plan historico de migracion y decisiones de arquitectura Android.",
  },
  {
    id: "android-parity",
    group: "android_app",
    title: "Android parity checklist",
    pathLabel: "docs/android-parity-checklist.md",
    summary: "Checklist de paridad entre web y Android.",
  },
  {
    id: "android-phase-playbook",
    group: "android_app",
    title: "Android phase playbook",
    pathLabel: "docs/android-phase-playbook.md",
    summary: "Playbook por fases para despliegues y validaciones Android.",
  },
  {
    id: "android-support-cleanup-pending",
    group: "android_app",
    title: "Android support cleanup pending",
    pathLabel: "docs/referidos-system/android-support-cleanup-pending.md",
    summary: "Pendientes historicos del bridge de soporte y macros en Android.",
  },
] as const;

export const ADMIN_LEGAL_DOCS = [
  {
    id: "legal-index",
    title: "Indice legal",
    pathLabel: "docs/legal/README.md",
    documentId: "legal.index",
    version: "repo",
    summary: "Indice de documentacion legal y referencias internas.",
  },
  {
    id: "legal-brand-policy",
    title: "Politica legal de iconos",
    pathLabel: "docs/legal/brand-icon-policy.md",
    documentId: "legal.brand_icon_policy",
    version: "repo",
    summary: "Politica de uso de logos, iconos y marcas de terceros.",
  },
  {
    id: "legal-brand-manifest",
    title: "Manifiesto legal de marcas",
    pathLabel: "docs/legal/brand-icon-manifest.md",
    documentId: "legal.brand_icon_manifest",
    version: "repo",
    summary: "Manifest y trazabilidad de aprobaciones/restricciones de marcas.",
  },
  {
    id: "legal-privacy-es",
    title: "Privacidad (ES)",
    pathLabel: "packages/legal-content/content/es/privacy.md",
    documentId: "legal.user.privacy.es",
    version: "content",
    summary: "Politica de privacidad en espanol.",
  },
  {
    id: "legal-terms-es",
    title: "Terminos y condiciones (ES)",
    pathLabel: "packages/legal-content/content/es/terms.md",
    documentId: "legal.user.terms.es",
    version: "content",
    summary: "Terminos de uso para usuarios finales en espanol.",
  },
  {
    id: "legal-data-deletion-es",
    title: "Borrado de datos (ES)",
    pathLabel: "packages/legal-content/content/es/data-deletion.md",
    documentId: "legal.user.data_deletion.es",
    version: "content",
    summary: "Procedimiento y alcance de eliminacion de datos en espanol.",
  },
  {
    id: "legal-privacy-en",
    title: "Privacy (EN)",
    pathLabel: "packages/legal-content/content/en/privacy.md",
    documentId: "legal.user.privacy.en",
    version: "content",
    summary: "Privacy policy in English.",
  },
  {
    id: "legal-terms-en",
    title: "Terms and conditions (EN)",
    pathLabel: "packages/legal-content/content/en/terms.md",
    documentId: "legal.user.terms.en",
    version: "content",
    summary: "Terms and conditions in English.",
  },
  {
    id: "legal-data-deletion-en",
    title: "Data deletion (EN)",
    pathLabel: "packages/legal-content/content/en/data-deletion.md",
    documentId: "legal.user.data_deletion.en",
    version: "content",
    summary: "Data deletion policy in English.",
  },
] as const;

export const ADMIN_LEGAL_POLICY_SUMMARY = {
  owner: "legal-and-observability",
  reviewIntervalDays: 90,
  totalEntries: ADMIN_LEGAL_DOCS.length,
  contentDocs: ADMIN_LEGAL_DOCS.filter((item) => item.version === "content").length,
  repoDocs: ADMIN_LEGAL_DOCS.filter((item) => item.version === "repo").length,
} as const;
